# Generated by Django 4.2 on 2026-01-11 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentistas', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('agendamentos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['data_hora']},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentistas.dentista'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='agendado', max_length=20),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_consulta',
            field=models.CharField(choices=[('avaliacao', 'Avaliação'), ('limpeza', 'Limpeza'), ('restauracao', 'Restauração'), ('extracao', 'Extração'), ('outros', 'Outros')], default='avaliacao', max_length=20),
        ),
    ]
